// src/components/Footer.tsx
'use client';
import { Link } from '@heroui/react';

const repoUrl = process.env.NEXT_PUBLIC_REPO_URL!;

export default function Footer() {
  return (
    <footer className="flex justify-center">
      <Link
        href={repoUrl}
        target="_blank"
        color="foreground"
        size="sm"
        underline="hover"
        className="opacity-75"
      >
        source code
      </Link>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer class="p-4 flex justify-center">
    <p class="text-sm opacity-75">
      baxthus • <a
        href="https://github.com/baxthus/bio-link"
        target="blank"
        rel="noopener noreferrer nofollow"
        class="underline hover:text-violet-400 transition-colors"
      >source code</a>
    </p>
  </footer>
</template>
