// src/lib/components/header.svelte
<script lang="ts">
  const links: {
    name: string;
    to: string;
  }[] = [
    { name: 'home', to: '/' },
    { name: 'blog', to: '/blog' },
  ];
</script>

<header class="flex justify-between">
  <h1 class="block font-bold after:-mt-1.5 after:block after:content-['=======']">baxthus</h1>
  <div class="flex">
    {#each links as link}
      <a class="font-bold" href={link.to}>{link.name}</a>
      {#if link !== links[links.length - 1]}
        <span class="mx-2 font-bold">|</span>
      {/if}
    {/each}
  </div>
</header>

// src/components/header.tsx
import { Link } from '@tanstack/react-router';
import { Fragment } from 'react/jsx-runtime';

const links: {
  name: string;
  to: string;
}[] = [
  { name: 'home', to: '/' },
  { name: 'blog', to: '/blog' },
];

export function Header() {
  return (
    <header className="flex justify-between">
      <h1 className="block font-bold after:-mt-1.5 after:block after:content-['=======']">
        baxthus
      </h1>
      <div>
        {links.map((link) => (
          <Fragment key={link.name}>
            <Link className="font-bold" to={link.to}>
              {link.name}
            </Link>
            {link !== links[links.length - 1] && <span className="mx-2 font-bold">|</span>}
          </Fragment>
        ))}
      </div>
    </header>
  );
}
