// src/components/Spotify.tsx
import {
  Card,
  CardBody,
  CardHeader,
  Link,
  Progress,
  Tooltip,
} from '@heroui/react';
import { IconBrandSpotify } from '@tabler/icons-react';
import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';
import type { Types } from 'use-lanyard';

export default function Spotify({ spotify }: { spotify: Types.Spotify }) {
  const [now, setNow] = useState(new Date());

  useEffect(() => {
    const interval = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(interval);
  }, []);

  const progress = useMemo(() => {
    const start = spotify.timestamps?.start ?? now;
    const end = spotify.timestamps?.end ?? now;

    if (end <= start) return 0;

    const progress = ((now.getTime() - start) / (end - start)) * 100;
    return Math.min(Math.max(progress, 0), 100);
  }, [now, spotify.timestamps]);

  return (
    <Card className="w-full max-w-sm">
      <CardHeader className="pb-0">
        <div className="flex w-full flex-row items-center justify-between">
          <p className="text-sm font-medium">Listening to Spotify</p>
          <Tooltip content="Data may be outdated">
            <IconBrandSpotify size={20} />
          </Tooltip>
        </div>
      </CardHeader>
      <CardBody>
        <div className="flex w-full flex-row gap-x-4">
          <Tooltip content={spotify.album}>
            <Image
              src={spotify.album_art_url ?? ''}
              alt={spotify.album ?? 'Album Art'}
              width={96}
              height={96}
            />
          </Tooltip>
          <div className="flex w-full min-w-0 flex-col">
            <div className="flex h-full flex-col justify-center">
              <Link
                color="foreground"
                underline="hover"
                href={`https://open.spotify.com/track/${spotify.track_id}`}
                target="_blank"
                className="block truncate font-bold"
              >
                {spotify.song}
              </Link>
              <p className="text-default-600 truncate text-sm">
                {spotify.artist?.replace(';', ', ')}
              </p>
            </div>
            <Progress
              aria-label="Song Progress"
              value={progress}
              size="sm"
              color="success"
              className="mt-2 mb-0.5"
            />
          </div>
        </div>
      </CardBody>
    </Card>
  );
}

// src/components/Spotify.vue
<script setup lang="ts">
import type { LanyardData } from '~/types/lanyard';

const { data } = defineProps(['data']) as { data: LanyardData };

const now = ref(new Date().getTime());

setInterval(() => {
  now.value = new Date().getTime();
}, 1000);

function getProgress() {
  const start = data.spotify?.timestamps.start ?? new Date().getTime();
  const end = data.spotify?.timestamps.end ?? new Date().getTime();

  if (end <= start) return 0;

  const progress = ((now.value - start) / (end - start)) * 100;
  return Math.min(Math.max(progress, 0), 100); // Ensure progress is between 0 and 100
}
</script>

<template>
  <Box>
    <template #title>
      Listening to Spotify
    </template>
    <div class="flex flex-row gap-x-4">
      <img
        v-tooltip.top="{
          value: data?.spotify?.album,
          autoHide: false,
        }"
        :src="data?.spotify?.album_art_url"
        alt="Album Art"
        class="rounded-lg h-24 w-24"
      >
      <div class="flex flex-col items-start justify-center gap-2 min-w-0">
        <a
          :href="'https://open.spotify.com/track/' + data?.spotify?.track_id"
          target="_blank"
          rel="noopener noreferrer nofollow"
          class="font-bold text-lg truncate w-full hover:text-green-400 hover:underline transition-colors cursor-pointer"
        >
          {{ data?.spotify?.song }}
        </a>
        <p class="truncate w-full">
          {{ data?.spotify?.artist.replace(/;/g, ', ') }}
        </p>
      </div>
    </div>
    <div class="flex flex-row items-center gap-x-2">
      <div class="w-full bg-subtext1 h-1 rounded-full">
        <div
          class="bg-violet-300 h-1 rounded-full"
          :style="{ width: getProgress() + '%' }"
        />
      </div>
    </div>
  </Box>
</template>
